fun_facts = ["Ethiopia’s Danakil Depression is the hottest place on Earth.","Ethiopia is home to the lowest place on the African continent, the Danakil Depression.","They run on their own calendar","It was the birthplace of coffee!", "Ethiopian man, Abebe Bikila, was the first black African to win gold at the Olympics!","Addis Ababa is the highest capital city in Africa", "You’ll find lots of vegetarian cuisine in Ethiopia","Ethiopia was never colonised by the Europeans", "Over 80 languages are spoken in the country"] 
print("_________________________")
print("Want to read a fun fact")
print("________________________")
input()
print(fun_facts[0])
print("________________________")
input()
print(fun_facts[1])
print("________________________")
input()
print(fun_facts[3])
print("________________________")
input()
print(fun_facts[4])
print("________________________")
input()
print(fun_facts[5])
print("________________________")
input()
print(fun_facts[6])
print("________________________")
input()
print(fun_facts[7])
print("________________________")
input()
print(fun_facts[8])
input()
print("______________________")
print("Think you for reading")
print("________________________")